### ISSUE TITLE
`&#13;` in SAML response not sanitized before validation

### ISSUE THREAD

**Issue by ichi234** [boxyhq/saml20#599]
### Summary
When validating a SAML response, if a newline in the response is `&#13;` instead of `&#xD;`, it is not sanitized and the validation fails.

### Environment in which the event occurred
- Browser: Microsoft Edge on Windows 10
- Execution environment: Next.js application on WSL

### Related Library Versions
```
"@boxyhq/saml20": "1.5.1"
"@boxyhq/saml-jackson": "1.26.1"
"next-auth": "4.24.7"
```

### Detailed Situation
In the case in issue, the `X509Certificate` portion of the xml argument passed to the validateSignature.hasValidSignature method represented line breaks as `&#13;`.
This representation is not sanitized before use and therefore fails validation.

Actual response data (excerpts)
```
<KeyInfo><X509Data><X509Certificate>MIID2TCCAsGgAwIBAgIBAzANBgkqhkiG9w0BAQsFADBvMQswCQYDVQQGEwJKUDERMA8GA1UECAwI&#13;
SE9ra2FpZG8xFDASBgNVBAcMC1NBUFBPUk8tU0hJMSowKAYDVQQKDCFIb2trYWlkbyBFbGVjdHJp&#13;
YyBQb3dlciBDby4sIEluYy4xCzAJBgNVBAMMAmNhMCAXDTIxMDMwMzAwMzgyMVoYDzIwNTEwMjI0&#13;
MDAzODIxWjByMQswCQYDVQQGEwJKUDERMA8GA1UECAwISE9ra2FpZG8xKjAoBgNVBAoMIUhva2th&#13;
...
vs1WiMb2KXjA5d/xGzkvmxl9Ng6Ama6p3sg38AaLcB72WCNRo5PSYL3aRta5GyfaIAeohJk1Lne+&#13;
neTrBOIBI/dbYuEe9oHPr/IW9fffE4X0iGqBVMy4UzMxIM/DNEmcp7ixVm/u6ybCDbGVWBezSVFy&#13;
SBDO6kbSaR5BAQlvMoF9+3Wixyv7Q3JomUDe7nnp2JrSvh2T1+8tFQWkEa9/1JkJT3O6XrBeY8Me&#13;
n4P9U4e8TThs3VH1lBRV8T1NYUs=</X509Certificate></X509Data></KeyInfo>
```

### Proposed Solution
By manually modifying the contents under `node_modules` for testing, the following adjustment was found to resolve the issue:

- Original code (problematic part):
https://github.com/boxyhq/saml20/blob/main/lib/validateSignature.ts#L26
```
xml = xml.replace(/&#x(d|D);/gi, '');
```

- Suggested modification:
```
xml = xml.replace(/(&#x(d|D);|&#13;)/gi, '');
```

This modification ensures that `&#13;` is appropriately sanitized, allowing the validation to proceed correctly.

**Comment by rileyw** [comment]
@ichi234 Would you check that this test case matches the SAML response that you have observed to be problematic? https://github.com/rileyw/saml20/blob/issue/599/test/assets/saml20.validResponseSignedMessage-unsanitized.xml#L7-L19

**Comment by VuBui83** [comment]
Facing same issue, I found another solution, loadSignature can take in a node or string, remove the toString solved it for me
https://github.com/boxyhq/saml20/blob/4a2b5f6140a46e6bdfff8abccc0166787e07eeb7/lib/validateSignature.ts#L61

**Comment by deepakprabhakara** [comment]
Apologies for missing this issue, we'll look into it right away. It looks like we should let the library handle it as suggested by @VuBui83

**Comment by deepakprabhakara** [comment]
@rileyw @VuBui83 https://github.com/boxyhq/saml20/pull/748 seems to fix it
